//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPN
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustTrans", Namespace="http://schemas.datacontract.org/2004/07/CloudCollectService.Data", IsReference=true)]
    public partial class CustTrans : object
    {
        
        private SPN.AnAssociate AssociateField;
        
        private string AssociateNoField;
        
        private int AuditNoField;
        
        private string CustomerKidField;
        
        private string CustomerNoField;
        
        private System.DateTime Date1Field;
        
        private System.DateTime Date2Field;
        
        private string DebitorNrField;
        
        private int DueDateField;
        
        private System.DateTime DueDateDateField;
        
        private string ErrorMessageField;
        
        private string ExternalRef1Field;
        
        private string ExternalRef2Field;
        
        private string ExternalRef3Field;
        
        private string Free1Field;
        
        private string Free2Field;
        
        private string Free3Field;
        
        private string Free4Field;
        
        private string Free5Field;
        
        private bool FreeBool1Field;
        
        private bool FreeBool2Field;
        
        private int FreeNum1Field;
        
        private int FreeNum2Field;
        
        private int FreeNum3Field;
        
        private System.DateTime InterestFromDateField;
        
        private string InvoiceNoField;
        
        private bool IsForInkCaseField;
        
        private string KreditorNrField;
        
        private System.DateTime LastReminderDateField;
        
        private string NoOfRemindersSentField;
        
        private string OrderNoField;
        
        private decimal OriginalAmmountField;
        
        private decimal OutstandingAmmountField;
        
        private int PaidStatusField;
        
        private string SaksNrField;
        
        private string TextField;
        
        private bool TilInnsendingField;
        
        private SPN.AVoucher VoucherField;
        
        private int VoucherJournalNoField;
        
        private string VoucherNoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SPN.AnAssociate Associate
        {
            get
            {
                return this.AssociateField;
            }
            set
            {
                this.AssociateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AssociateNo
        {
            get
            {
                return this.AssociateNoField;
            }
            set
            {
                this.AssociateNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AuditNo
        {
            get
            {
                return this.AuditNoField;
            }
            set
            {
                this.AuditNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerKid
        {
            get
            {
                return this.CustomerKidField;
            }
            set
            {
                this.CustomerKidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerNo
        {
            get
            {
                return this.CustomerNoField;
            }
            set
            {
                this.CustomerNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date1
        {
            get
            {
                return this.Date1Field;
            }
            set
            {
                this.Date1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date2
        {
            get
            {
                return this.Date2Field;
            }
            set
            {
                this.Date2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DebitorNr
        {
            get
            {
                return this.DebitorNrField;
            }
            set
            {
                this.DebitorNrField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DueDate
        {
            get
            {
                return this.DueDateField;
            }
            set
            {
                this.DueDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DueDateDate
        {
            get
            {
                return this.DueDateDateField;
            }
            set
            {
                this.DueDateDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage
        {
            get
            {
                return this.ErrorMessageField;
            }
            set
            {
                this.ErrorMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExternalRef1
        {
            get
            {
                return this.ExternalRef1Field;
            }
            set
            {
                this.ExternalRef1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExternalRef2
        {
            get
            {
                return this.ExternalRef2Field;
            }
            set
            {
                this.ExternalRef2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExternalRef3
        {
            get
            {
                return this.ExternalRef3Field;
            }
            set
            {
                this.ExternalRef3Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Free1
        {
            get
            {
                return this.Free1Field;
            }
            set
            {
                this.Free1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Free2
        {
            get
            {
                return this.Free2Field;
            }
            set
            {
                this.Free2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Free3
        {
            get
            {
                return this.Free3Field;
            }
            set
            {
                this.Free3Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Free4
        {
            get
            {
                return this.Free4Field;
            }
            set
            {
                this.Free4Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Free5
        {
            get
            {
                return this.Free5Field;
            }
            set
            {
                this.Free5Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool FreeBool1
        {
            get
            {
                return this.FreeBool1Field;
            }
            set
            {
                this.FreeBool1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool FreeBool2
        {
            get
            {
                return this.FreeBool2Field;
            }
            set
            {
                this.FreeBool2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FreeNum1
        {
            get
            {
                return this.FreeNum1Field;
            }
            set
            {
                this.FreeNum1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FreeNum2
        {
            get
            {
                return this.FreeNum2Field;
            }
            set
            {
                this.FreeNum2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FreeNum3
        {
            get
            {
                return this.FreeNum3Field;
            }
            set
            {
                this.FreeNum3Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime InterestFromDate
        {
            get
            {
                return this.InterestFromDateField;
            }
            set
            {
                this.InterestFromDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InvoiceNo
        {
            get
            {
                return this.InvoiceNoField;
            }
            set
            {
                this.InvoiceNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsForInkCase
        {
            get
            {
                return this.IsForInkCaseField;
            }
            set
            {
                this.IsForInkCaseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KreditorNr
        {
            get
            {
                return this.KreditorNrField;
            }
            set
            {
                this.KreditorNrField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastReminderDate
        {
            get
            {
                return this.LastReminderDateField;
            }
            set
            {
                this.LastReminderDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NoOfRemindersSent
        {
            get
            {
                return this.NoOfRemindersSentField;
            }
            set
            {
                this.NoOfRemindersSentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderNo
        {
            get
            {
                return this.OrderNoField;
            }
            set
            {
                this.OrderNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal OriginalAmmount
        {
            get
            {
                return this.OriginalAmmountField;
            }
            set
            {
                this.OriginalAmmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal OutstandingAmmount
        {
            get
            {
                return this.OutstandingAmmountField;
            }
            set
            {
                this.OutstandingAmmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PaidStatus
        {
            get
            {
                return this.PaidStatusField;
            }
            set
            {
                this.PaidStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SaksNr
        {
            get
            {
                return this.SaksNrField;
            }
            set
            {
                this.SaksNrField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Text
        {
            get
            {
                return this.TextField;
            }
            set
            {
                this.TextField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool TilInnsending
        {
            get
            {
                return this.TilInnsendingField;
            }
            set
            {
                this.TilInnsendingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SPN.AVoucher Voucher
        {
            get
            {
                return this.VoucherField;
            }
            set
            {
                this.VoucherField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int VoucherJournalNo
        {
            get
            {
                return this.VoucherJournalNoField;
            }
            set
            {
                this.VoucherJournalNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VoucherNo
        {
            get
            {
                return this.VoucherNoField;
            }
            set
            {
                this.VoucherNoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AnAssociate", Namespace="http://schemas.datacontract.org/2004/07/CloudCollectService.Data", IsReference=true)]
    public partial class AnAssociate : object
    {
        
        private SPN.AddressInfo AddressField;
        
        private int AsscNoField;
        
        private string BankAccountField;
        
        private string CustNoField;
        
        private string DebitorNrField;
        
        private string EuVatRegNoField;
        
        private string IdentField;
        
        private bool IsCoorporateField;
        
        private string LanguageField;
        
        private string NameField;
        
        private string PhoneNoField;
        
        private bool VatLiableField;
        
        private string WebPageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SPN.AddressInfo Address
        {
            get
            {
                return this.AddressField;
            }
            set
            {
                this.AddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AsscNo
        {
            get
            {
                return this.AsscNoField;
            }
            set
            {
                this.AsscNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BankAccount
        {
            get
            {
                return this.BankAccountField;
            }
            set
            {
                this.BankAccountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustNo
        {
            get
            {
                return this.CustNoField;
            }
            set
            {
                this.CustNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DebitorNr
        {
            get
            {
                return this.DebitorNrField;
            }
            set
            {
                this.DebitorNrField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EuVatRegNo
        {
            get
            {
                return this.EuVatRegNoField;
            }
            set
            {
                this.EuVatRegNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ident
        {
            get
            {
                return this.IdentField;
            }
            set
            {
                this.IdentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsCoorporate
        {
            get
            {
                return this.IsCoorporateField;
            }
            set
            {
                this.IsCoorporateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Language
        {
            get
            {
                return this.LanguageField;
            }
            set
            {
                this.LanguageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNo
        {
            get
            {
                return this.PhoneNoField;
            }
            set
            {
                this.PhoneNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool VatLiable
        {
            get
            {
                return this.VatLiableField;
            }
            set
            {
                this.VatLiableField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WebPage
        {
            get
            {
                return this.WebPageField;
            }
            set
            {
                this.WebPageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AVoucher", Namespace="http://schemas.datacontract.org/2004/07/CloudCollectService.Data", IsReference=true)]
    public partial class AVoucher : object
    {
        
        private decimal AmmountInCurrencyField;
        
        private SPN.AnAssociate AssociateField;
        
        private string CurrencyNoField;
        
        private int CustomerNoField;
        
        private string DueDateField;
        
        private string InvoiceNoField;
        
        private string OrderNoField;
        
        private int VoucherDateField;
        
        private int VoucherNoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal AmmountInCurrency
        {
            get
            {
                return this.AmmountInCurrencyField;
            }
            set
            {
                this.AmmountInCurrencyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SPN.AnAssociate Associate
        {
            get
            {
                return this.AssociateField;
            }
            set
            {
                this.AssociateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CurrencyNo
        {
            get
            {
                return this.CurrencyNoField;
            }
            set
            {
                this.CurrencyNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CustomerNo
        {
            get
            {
                return this.CustomerNoField;
            }
            set
            {
                this.CustomerNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DueDate
        {
            get
            {
                return this.DueDateField;
            }
            set
            {
                this.DueDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InvoiceNo
        {
            get
            {
                return this.InvoiceNoField;
            }
            set
            {
                this.InvoiceNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderNo
        {
            get
            {
                return this.OrderNoField;
            }
            set
            {
                this.OrderNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int VoucherDate
        {
            get
            {
                return this.VoucherDateField;
            }
            set
            {
                this.VoucherDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int VoucherNo
        {
            get
            {
                return this.VoucherNoField;
            }
            set
            {
                this.VoucherNoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddressInfo", Namespace="http://schemas.datacontract.org/2004/07/CloudCollectService.Data", IsReference=true)]
    public partial class AddressInfo : object
    {
        
        private string Address1Field;
        
        private string Address2Field;
        
        private string CityField;
        
        private string CountryCodeField;
        
        private string EmailField;
        
        private string ZipCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address1
        {
            get
            {
                return this.Address1Field;
            }
            set
            {
                this.Address1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address2
        {
            get
            {
                return this.Address2Field;
            }
            set
            {
                this.Address2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City
        {
            get
            {
                return this.CityField;
            }
            set
            {
                this.CityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CountryCode
        {
            get
            {
                return this.CountryCodeField;
            }
            set
            {
                this.CountryCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZipCode
        {
            get
            {
                return this.ZipCodeField;
            }
            set
            {
                this.ZipCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CaseStatus", Namespace="http://schemas.datacontract.org/2004/07/CloudCollectService.Data", IsReference=true)]
    public partial class CaseStatus : object
    {
        
        private string CaseNumberField;
        
        private bool HasChangesInDateRangeField;
        
        private bool HasNewCaseStatusField;
        
        private bool HasNewMessagesField;
        
        private bool HasNewPaymentsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CaseNumber
        {
            get
            {
                return this.CaseNumberField;
            }
            set
            {
                this.CaseNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasChangesInDateRange
        {
            get
            {
                return this.HasChangesInDateRangeField;
            }
            set
            {
                this.HasChangesInDateRangeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasNewCaseStatus
        {
            get
            {
                return this.HasNewCaseStatusField;
            }
            set
            {
                this.HasNewCaseStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasNewMessages
        {
            get
            {
                return this.HasNewMessagesField;
            }
            set
            {
                this.HasNewMessagesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasNewPayments
        {
            get
            {
                return this.HasNewPaymentsField;
            }
            set
            {
                this.HasNewPaymentsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InkassoSak", Namespace="http://schemas.datacontract.org/2004/07/CloudCollectService.Data", IsReference=true)]
    public partial class InkassoSak : object
    {
        
        private int AntallSakerTotDebField;
        
        private SPN.AnAssociate AssociateField;
        
        private System.DateTime AvsluttetDatoField;
        
        private double BalanceCapitalField;
        
        private double BalanceEFeeField;
        
        private double BalanceFFeeField;
        
        private double BalanceInterestField;
        
        private double BalanceRSaleryField;
        
        private double BalanceTSaleryField;
        
        private double CapitalField;
        
        private string CaseWorkerField;
        
        private string DebitorNrField;
        
        private decimal HovedstolField;
        
        private System.DateTime InnsendtDatoField;
        
        private decimal InteresetFeeField;
        
        private string KategoriField;
        
        private string KreditorNrField;
        
        private string LastMsgField;
        
        private int LastStepField;
        
        private double PaidCapitalField;
        
        private double PaidCostInterestField;
        
        private double PaidEFeeField;
        
        private double PaidFFeeField;
        
        private double PaidInterestField;
        
        private double PaidRSaleryField;
        
        private double PaidTSaleryField;
        
        private string SaksNrField;
        
        private string StatusField;
        
        private string StatusTextField;
        
        private double TotaltSkyldigDebField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AntallSakerTotDeb
        {
            get
            {
                return this.AntallSakerTotDebField;
            }
            set
            {
                this.AntallSakerTotDebField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SPN.AnAssociate Associate
        {
            get
            {
                return this.AssociateField;
            }
            set
            {
                this.AssociateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime AvsluttetDato
        {
            get
            {
                return this.AvsluttetDatoField;
            }
            set
            {
                this.AvsluttetDatoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double BalanceCapital
        {
            get
            {
                return this.BalanceCapitalField;
            }
            set
            {
                this.BalanceCapitalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double BalanceEFee
        {
            get
            {
                return this.BalanceEFeeField;
            }
            set
            {
                this.BalanceEFeeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double BalanceFFee
        {
            get
            {
                return this.BalanceFFeeField;
            }
            set
            {
                this.BalanceFFeeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double BalanceInterest
        {
            get
            {
                return this.BalanceInterestField;
            }
            set
            {
                this.BalanceInterestField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double BalanceRSalery
        {
            get
            {
                return this.BalanceRSaleryField;
            }
            set
            {
                this.BalanceRSaleryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double BalanceTSalery
        {
            get
            {
                return this.BalanceTSaleryField;
            }
            set
            {
                this.BalanceTSaleryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Capital
        {
            get
            {
                return this.CapitalField;
            }
            set
            {
                this.CapitalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CaseWorker
        {
            get
            {
                return this.CaseWorkerField;
            }
            set
            {
                this.CaseWorkerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DebitorNr
        {
            get
            {
                return this.DebitorNrField;
            }
            set
            {
                this.DebitorNrField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Hovedstol
        {
            get
            {
                return this.HovedstolField;
            }
            set
            {
                this.HovedstolField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime InnsendtDato
        {
            get
            {
                return this.InnsendtDatoField;
            }
            set
            {
                this.InnsendtDatoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal InteresetFee
        {
            get
            {
                return this.InteresetFeeField;
            }
            set
            {
                this.InteresetFeeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Kategori
        {
            get
            {
                return this.KategoriField;
            }
            set
            {
                this.KategoriField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KreditorNr
        {
            get
            {
                return this.KreditorNrField;
            }
            set
            {
                this.KreditorNrField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastMsg
        {
            get
            {
                return this.LastMsgField;
            }
            set
            {
                this.LastMsgField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LastStep
        {
            get
            {
                return this.LastStepField;
            }
            set
            {
                this.LastStepField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double PaidCapital
        {
            get
            {
                return this.PaidCapitalField;
            }
            set
            {
                this.PaidCapitalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double PaidCostInterest
        {
            get
            {
                return this.PaidCostInterestField;
            }
            set
            {
                this.PaidCostInterestField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double PaidEFee
        {
            get
            {
                return this.PaidEFeeField;
            }
            set
            {
                this.PaidEFeeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double PaidFFee
        {
            get
            {
                return this.PaidFFeeField;
            }
            set
            {
                this.PaidFFeeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double PaidInterest
        {
            get
            {
                return this.PaidInterestField;
            }
            set
            {
                this.PaidInterestField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double PaidRSalery
        {
            get
            {
                return this.PaidRSaleryField;
            }
            set
            {
                this.PaidRSaleryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double PaidTSalery
        {
            get
            {
                return this.PaidTSaleryField;
            }
            set
            {
                this.PaidTSaleryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SaksNr
        {
            get
            {
                return this.SaksNrField;
            }
            set
            {
                this.SaksNrField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusText
        {
            get
            {
                return this.StatusTextField;
            }
            set
            {
                this.StatusTextField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double TotaltSkyldigDeb
        {
            get
            {
                return this.TotaltSkyldigDebField;
            }
            set
            {
                this.TotaltSkyldigDebField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VismaBilag", Namespace="http://schemas.datacontract.org/2004/07/CloudCollectService.Data", IsReference=true)]
    public partial class VismaBilag : object
    {
        
        private decimal AmmountField;
        
        private decimal BetaltAmmHovedstolField;
        
        private decimal BetaltAmmMomsField;
        
        private decimal BetaltAmmProvisjonHsField;
        
        private decimal BetaltAmmProvisjonRenteField;
        
        private decimal BetaltAmmRenteField;
        
        private decimal BetaltAmmReturRettsgebyrField;
        
        private decimal BetaltAmmUtbetaltField;
        
        private string BilagArtField;
        
        private string BuntNrField;
        
        private string CaseNoPredField;
        
        private string CrmRef1Field;
        
        private string DebetKontoField;
        
        private string FakturaNrField;
        
        private SPN.VismaBilagInvoice[] FakturaerField;
        
        private string KidField;
        
        private string KreditKontoField;
        
        private SPN.CustTrans TransaksjonenField;
        
        private long[] UnikFeltField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Ammount
        {
            get
            {
                return this.AmmountField;
            }
            set
            {
                this.AmmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal BetaltAmmHovedstol
        {
            get
            {
                return this.BetaltAmmHovedstolField;
            }
            set
            {
                this.BetaltAmmHovedstolField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal BetaltAmmMoms
        {
            get
            {
                return this.BetaltAmmMomsField;
            }
            set
            {
                this.BetaltAmmMomsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal BetaltAmmProvisjonHs
        {
            get
            {
                return this.BetaltAmmProvisjonHsField;
            }
            set
            {
                this.BetaltAmmProvisjonHsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal BetaltAmmProvisjonRente
        {
            get
            {
                return this.BetaltAmmProvisjonRenteField;
            }
            set
            {
                this.BetaltAmmProvisjonRenteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal BetaltAmmRente
        {
            get
            {
                return this.BetaltAmmRenteField;
            }
            set
            {
                this.BetaltAmmRenteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal BetaltAmmReturRettsgebyr
        {
            get
            {
                return this.BetaltAmmReturRettsgebyrField;
            }
            set
            {
                this.BetaltAmmReturRettsgebyrField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal BetaltAmmUtbetalt
        {
            get
            {
                return this.BetaltAmmUtbetaltField;
            }
            set
            {
                this.BetaltAmmUtbetaltField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BilagArt
        {
            get
            {
                return this.BilagArtField;
            }
            set
            {
                this.BilagArtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BuntNr
        {
            get
            {
                return this.BuntNrField;
            }
            set
            {
                this.BuntNrField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CaseNoPred
        {
            get
            {
                return this.CaseNoPredField;
            }
            set
            {
                this.CaseNoPredField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CrmRef1
        {
            get
            {
                return this.CrmRef1Field;
            }
            set
            {
                this.CrmRef1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DebetKonto
        {
            get
            {
                return this.DebetKontoField;
            }
            set
            {
                this.DebetKontoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FakturaNr
        {
            get
            {
                return this.FakturaNrField;
            }
            set
            {
                this.FakturaNrField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SPN.VismaBilagInvoice[] Fakturaer
        {
            get
            {
                return this.FakturaerField;
            }
            set
            {
                this.FakturaerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Kid
        {
            get
            {
                return this.KidField;
            }
            set
            {
                this.KidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KreditKonto
        {
            get
            {
                return this.KreditKontoField;
            }
            set
            {
                this.KreditKontoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SPN.CustTrans Transaksjonen
        {
            get
            {
                return this.TransaksjonenField;
            }
            set
            {
                this.TransaksjonenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long[] UnikFelt
        {
            get
            {
                return this.UnikFeltField;
            }
            set
            {
                this.UnikFeltField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VismaBilagInvoice", Namespace="http://schemas.datacontract.org/2004/07/CloudCollectService.Data")]
    public partial class VismaBilagInvoice : object
    {
        
        private string FakturaNrField;
        
        private decimal KapitalField;
        
        private decimal RenterField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FakturaNr
        {
            get
            {
                return this.FakturaNrField;
            }
            set
            {
                this.FakturaNrField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Kapital
        {
            get
            {
                return this.KapitalField;
            }
            set
            {
                this.KapitalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Renter
        {
            get
            {
                return this.RenterField;
            }
            set
            {
                this.RenterField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DirectPaymentImport", Namespace="http://schemas.datacontract.org/2004/07/CloudCollectService.Data", IsReference=true)]
    public partial class DirectPaymentImport : object
    {
        
        private string AccountNoField;
        
        private string ActionTypeField;
        
        private decimal AmountField;
        
        private string CaseNoField;
        
        private string CreditorNumberField;
        
        private string Free1Field;
        
        private string Free3Field;
        
        private bool FreeBool1Field;
        
        private bool FreeBool2Field;
        
        private decimal FreeNumeric1Field;
        
        private decimal FreeNumeric2Field;
        
        private decimal FreeNumeric3Field;
        
        private decimal FreeNumeric4Field;
        
        private bool ImportedField;
        
        private string InvoiceNoField;
        
        private string PaymentDateField;
        
        private string ReturnMessagesField;
        
        private string VoucherNoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountNo
        {
            get
            {
                return this.AccountNoField;
            }
            set
            {
                this.AccountNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ActionType
        {
            get
            {
                return this.ActionTypeField;
            }
            set
            {
                this.ActionTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Amount
        {
            get
            {
                return this.AmountField;
            }
            set
            {
                this.AmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CaseNo
        {
            get
            {
                return this.CaseNoField;
            }
            set
            {
                this.CaseNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreditorNumber
        {
            get
            {
                return this.CreditorNumberField;
            }
            set
            {
                this.CreditorNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Free1
        {
            get
            {
                return this.Free1Field;
            }
            set
            {
                this.Free1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Free3
        {
            get
            {
                return this.Free3Field;
            }
            set
            {
                this.Free3Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool FreeBool1
        {
            get
            {
                return this.FreeBool1Field;
            }
            set
            {
                this.FreeBool1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool FreeBool2
        {
            get
            {
                return this.FreeBool2Field;
            }
            set
            {
                this.FreeBool2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal FreeNumeric1
        {
            get
            {
                return this.FreeNumeric1Field;
            }
            set
            {
                this.FreeNumeric1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal FreeNumeric2
        {
            get
            {
                return this.FreeNumeric2Field;
            }
            set
            {
                this.FreeNumeric2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal FreeNumeric3
        {
            get
            {
                return this.FreeNumeric3Field;
            }
            set
            {
                this.FreeNumeric3Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal FreeNumeric4
        {
            get
            {
                return this.FreeNumeric4Field;
            }
            set
            {
                this.FreeNumeric4Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Imported
        {
            get
            {
                return this.ImportedField;
            }
            set
            {
                this.ImportedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InvoiceNo
        {
            get
            {
                return this.InvoiceNoField;
            }
            set
            {
                this.InvoiceNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaymentDate
        {
            get
            {
                return this.PaymentDateField;
            }
            set
            {
                this.PaymentDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReturnMessages
        {
            get
            {
                return this.ReturnMessagesField;
            }
            set
            {
                this.ReturnMessagesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VoucherNo
        {
            get
            {
                return this.VoucherNoField;
            }
            set
            {
                this.VoucherNoField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SPN.iCloudCollect")]
    public interface iCloudCollect
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iCloudCollect/Ping", ReplyAction="http://tempuri.org/iCloudCollect/PingResponse")]
        System.Threading.Tasks.Task<string> PingAsync(string value, string username, string password, string kreditorNr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iCloudCollect/TransferList", ReplyAction="http://tempuri.org/iCloudCollect/TransferListResponse")]
        System.Threading.Tasks.Task<SPN.CustTrans[]> TransferListAsync(SPN.CustTrans[] inputList, string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iCloudCollect/GetStatusOnDateRange", ReplyAction="http://tempuri.org/iCloudCollect/GetStatusOnDateRangeResponse")]
        System.Threading.Tasks.Task<SPN.CaseStatus[]> GetStatusOnDateRangeAsync(System.DateTime startDate, string creditorNumber, string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iCloudCollect/GetCaseInfoSpes", ReplyAction="http://tempuri.org/iCloudCollect/GetCaseInfoSpesResponse")]
        System.Threading.Tasks.Task<SPN.InkassoSak> GetCaseInfoSpesAsync(string kreditorNr, string associateNo, string saksNr, string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iCloudCollect/TransferForInkList", ReplyAction="http://tempuri.org/iCloudCollect/TransferForInkListResponse")]
        System.Threading.Tasks.Task<SPN.CustTrans[]> TransferForInkListAsync(SPN.CustTrans[] inputList, string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iCloudCollect/GetDummyCustTrans", ReplyAction="http://tempuri.org/iCloudCollect/GetDummyCustTransResponse")]
        System.Threading.Tasks.Task<SPN.CustTrans> GetDummyCustTransAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iCloudCollect/GetSettlementData", ReplyAction="http://tempuri.org/iCloudCollect/GetSettlementDataResponse")]
        System.Threading.Tasks.Task<SPN.VismaBilag[]> GetSettlementDataAsync(string kreditorNr, string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iCloudCollect/ImportDirectPayments", ReplyAction="http://tempuri.org/iCloudCollect/ImportDirectPaymentsResponse")]
        System.Threading.Tasks.Task<SPN.DirectPaymentImport[]> ImportDirectPaymentsAsync(SPN.DirectPaymentImport[] payments, string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iCloudCollect/MarkExportedSettlements", ReplyAction="http://tempuri.org/iCloudCollect/MarkExportedSettlementsResponse")]
        System.Threading.Tasks.Task<int> MarkExportedSettlementsAsync(string[] uniks, string kreditorNr, string username, string password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface iCloudCollectChannel : SPN.iCloudCollect, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class iCloudCollectClient : System.ServiceModel.ClientBase<SPN.iCloudCollect>, SPN.iCloudCollect
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public iCloudCollectClient() : 
                base(iCloudCollectClient.GetDefaultBinding(), iCloudCollectClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.WSHttpBinding_iCloudCollect.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public iCloudCollectClient(EndpointConfiguration endpointConfiguration) : 
                base(iCloudCollectClient.GetBindingForEndpoint(endpointConfiguration), iCloudCollectClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public iCloudCollectClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(iCloudCollectClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public iCloudCollectClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(iCloudCollectClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public iCloudCollectClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<string> PingAsync(string value, string username, string password, string kreditorNr)
        {
            return base.Channel.PingAsync(value, username, password, kreditorNr);
        }
        
        public System.Threading.Tasks.Task<SPN.CustTrans[]> TransferListAsync(SPN.CustTrans[] inputList, string username, string password)
        {
            return base.Channel.TransferListAsync(inputList, username, password);
        }
        
        public System.Threading.Tasks.Task<SPN.CaseStatus[]> GetStatusOnDateRangeAsync(System.DateTime startDate, string creditorNumber, string username, string password)
        {
            return base.Channel.GetStatusOnDateRangeAsync(startDate, creditorNumber, username, password);
        }
        
        public System.Threading.Tasks.Task<SPN.InkassoSak> GetCaseInfoSpesAsync(string kreditorNr, string associateNo, string saksNr, string username, string password)
        {
            return base.Channel.GetCaseInfoSpesAsync(kreditorNr, associateNo, saksNr, username, password);
        }
        
        public System.Threading.Tasks.Task<SPN.CustTrans[]> TransferForInkListAsync(SPN.CustTrans[] inputList, string username, string password)
        {
            return base.Channel.TransferForInkListAsync(inputList, username, password);
        }
        
        public System.Threading.Tasks.Task<SPN.CustTrans> GetDummyCustTransAsync()
        {
            return base.Channel.GetDummyCustTransAsync();
        }
        
        public System.Threading.Tasks.Task<SPN.VismaBilag[]> GetSettlementDataAsync(string kreditorNr, string username, string password)
        {
            return base.Channel.GetSettlementDataAsync(kreditorNr, username, password);
        }
        
        public System.Threading.Tasks.Task<SPN.DirectPaymentImport[]> ImportDirectPaymentsAsync(SPN.DirectPaymentImport[] payments, string username, string password)
        {
            return base.Channel.ImportDirectPaymentsAsync(payments, username, password);
        }
        
        public System.Threading.Tasks.Task<int> MarkExportedSettlementsAsync(string[] uniks, string kreditorNr, string username, string password)
        {
            return base.Channel.MarkExportedSettlementsAsync(uniks, kreditorNr, username, password);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WSHttpBinding_iCloudCollect))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TransportSecurityBindingElement userNameOverTransportSecurityBindingElement = System.ServiceModel.Channels.SecurityBindingElement.CreateUserNameOverTransportBindingElement();
                userNameOverTransportSecurityBindingElement.MessageSecurityVersion = System.ServiceModel.MessageSecurityVersion.WSSecurity11WSTrustFebruary2005WSSecureConversationFebruary2005WSSecurityPolicy11BasicSecurityProfile10;
                result.Elements.Add(userNameOverTransportSecurityBindingElement);
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WSHttpBinding_iCloudCollect))
            {
                return new System.ServiceModel.EndpointAddress("https://131109.web-site.no/CloudCollect/CloudCollect.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return iCloudCollectClient.GetBindingForEndpoint(EndpointConfiguration.WSHttpBinding_iCloudCollect);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return iCloudCollectClient.GetEndpointAddress(EndpointConfiguration.WSHttpBinding_iCloudCollect);
        }
        
        public enum EndpointConfiguration
        {
            
            WSHttpBinding_iCloudCollect,
        }
    }
}
